/*-------------------------------------------------------------------------
 * drawElements Quality Program Tester Core
 * ----------------------------------------
 *
 * Nintendo Switch entry point for dEQP.
 * Handles nxlink stdio redirection and default command-line arguments.
 *
 * All Switch-specific code lives here — tcuMain.cpp stays upstream-clean.
 *//*--------------------------------------------------------------------*/

#include "tcuDefs.hpp"
#include "tcuCommandLine.hpp"
#include "tcuPlatform.hpp"
#include "tcuApp.hpp"
#include "tcuResource.hpp"
#include "tcuTestLog.hpp"
#include "tcuTestSessionExecutor.hpp"
#include "deUniquePtr.hpp"
#include "qpDebugOut.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <csignal>
#include <switch.h>
#include <unistd.h>
#include <GLES2/gl2sgl.h>	/* sglShutdown() — release the GPU on exit */

static const char *s_sglChain = nullptr; /* runner to reload on exit, see main() */

/* TEMPORARY DEBUG: catch segfaults and print useful info */
static void crashHandler(int sig)
{
	const char *sigName = (sig == SIGSEGV) ? "SIGSEGV" : (sig == SIGABRT) ? "SIGABRT" : "SIGNAL";
	printf("\n[dEQP] *** CRASH: %s (signal %d) ***\n", sigName, sig);
	fflush(stdout);
	if (s_sglChain)
		envSetNextLoad(s_sglChain, s_sglChain);
	_exit(128 + sig);
}

// Implement this in your platform port.
tcu::Platform *createPlatform(void);

/*==========================================================================
 * nxlink stdio redirection
 *==========================================================================*/
static int s_nxlinkSock = -1;

static void initNxLink(void)
{
	if (R_FAILED(socketInitializeDefault()))
		return;

	s_nxlinkSock = nxlinkStdio();
	if (s_nxlinkSock >= 0)
		printf("printf output now goes to nxlink server\n");
	else
		socketExit();
}

static void deinitNxLink(void)
{
	if (s_nxlinkSock >= 0)
	{
		close(s_nxlinkSock);
		socketExit();
		s_nxlinkSock = -1;
	}
}

/*==========================================================================
 * romfs caselist support (sub-batch system).
 *
 * Tests are split into sub-batches of ~500 to fit in Switch memory.
 * Generated by: manage_tests.py generate-caselist current|pass
 * Build with:   elf2nro ... --romfsdir=framework/platform/switch/romfs
 *
 * Files in romfs:
 *   caselist_meta.txt   — single line: number of sub-batch files
 *   caselist_000.txt    — first sub-batch (trie notation)
 *   caselist_001.txt    — second sub-batch, etc.
 *
 * At startup, all files are copied to sdmc:/switch/ for std::ifstream access.
 * Each sub-batch runs in its own tcu::App instance, releasing test hierarchy
 * memory between batches.
 *
 * Falls back to a small inline caselist if romfs files are missing.
 *==========================================================================*/
static int s_numBatches = 0;
static bool s_romfsCaselistReady = false;

// Minimal fallback: just run info tests (inline, for when romfs is missing)
static const char *s_defaultCaselist =
	"--deqp-caselist="
	"{dEQP-GLES2{info{vendor,renderer,version,shading_language_version,extensions,render_target}}}";

static bool copyRomfsFile(const char *romfsPath, const char *sdmcPath)
{
	FILE *src = fopen(romfsPath, "r");
	if (!src) return false;

	fseek(src, 0, SEEK_END);
	long size = ftell(src);
	fseek(src, 0, SEEK_SET);

	if (size <= 0) { fclose(src); return false; }

	char *buf = (char *)malloc(size + 1);
	if (!buf) { fclose(src); return false; }

	size_t bytesRead = fread(buf, 1, size, src);
	fclose(src);

	FILE *dst = fopen(sdmcPath, "w");
	if (!dst) { free(buf); return false; }

	fwrite(buf, 1, bytesRead, dst);
	fclose(dst);
	free(buf);

	printf("[dEQP] Copied %s -> %s (%ld bytes)\n", romfsPath, sdmcPath, size);
	return true;
}

static void initRomfs(void)
{
	Result rc = romfsInit();
	if (R_FAILED(rc))
	{
		printf("[dEQP] romfsInit failed (0x%x), using fallback\n", rc);
		return;
	}

	// Read meta file for batch count
	FILE *meta = fopen("romfs:/caselist_meta.txt", "r");
	if (!meta)
	{
		printf("[dEQP] No caselist_meta.txt in romfs, using fallback\n");
		return;
	}
	if (fscanf(meta, "%d", &s_numBatches) != 1 || s_numBatches <= 0)
	{
		fclose(meta);
		printf("[dEQP] Invalid caselist_meta.txt, using fallback\n");
		s_numBatches = 0;
		return;
	}
	fclose(meta);

	// Copy each sub-batch file to SD card
	char romfsPath[128], sdmcPath[128];
	for (int i = 0; i < s_numBatches; i++)
	{
		snprintf(romfsPath, sizeof(romfsPath), "romfs:/caselist_%03d.txt", i);
		snprintf(sdmcPath, sizeof(sdmcPath), "sdmc:/switch/caselist_%03d.txt", i);

		if (!copyRomfsFile(romfsPath, sdmcPath))
		{
			printf("[dEQP] Failed to copy batch %d, truncating to %d batches\n", i, i);
			s_numBatches = i;
			break;
		}
	}

	if (s_numBatches > 0)
	{
		s_romfsCaselistReady = true;
		printf("[dEQP] Loaded %d sub-batch caselist files\n", s_numBatches);
	}
}

static void deinitRomfs(void)
{
	romfsExit();
}

/*==========================================================================
 * Run a single sub-batch of tests.
 * Creates CommandLine, DirArchive, TestLog, and App — all scoped so they
 * are destroyed (and memory freed) when the function returns.
 *==========================================================================*/
static bool runBatch(tcu::Platform &platform, int batchIndex, int totalBatches,
                     const char *caselistArg, const char *logFilename)
{
	printf("\n[dEQP] ========== Sub-batch %d/%d ==========\n", batchIndex + 1, totalBatches);
	fflush(stdout);

	const char *batchArgs[6];
	batchArgs[0] = "deqp-gles2";
	batchArgs[1] = caselistArg;
	batchArgs[2] = logFilename;
	batchArgs[3] = "--deqp-archive-dir=romfs:/";
	batchArgs[4] = "--deqp-log-images=disable";
	batchArgs[5] = "--deqp-watchdog=disable";

	try
	{
		tcu::CommandLine cmdLine(6, const_cast<char **>(batchArgs));
		tcu::DirArchive archive(cmdLine.getArchiveDir());
		tcu::TestLog log(cmdLine.getLogFileName(), cmdLine.getLogFlags());
		tcu::App app(platform, archive, log, cmdLine);

		printf("[dEQP] Running batch %d...\n", batchIndex + 1);
		fflush(stdout);

		int iterCount = 0;
		for (;;)
		{
			if (iterCount < 5 || (iterCount % 100) == 0)
			{
				printf("[dEQP] iterate #%d\n", iterCount);
				fflush(stdout);
			}
			if (!app.iterate())
				break;
			iterCount++;
			if (s_sglChain && (iterCount % 32) == 0)
			{
				/* runner log on SD: commit it regularly so a hard crash still leaves a
				 * recent position (every iteration made a full run far too slow) */
				fflush(stdout);
				fsync(fileno(stdout));
			}
		}
		printf("[dEQP] Batch %d finished after %d iterations\n", batchIndex + 1, iterCount);
		fflush(stdout);

		printf("[dEQP] Sub-batch %d/%d complete\n", batchIndex + 1, totalBatches);
		fflush(stdout);
		return true;
	}
	catch (const std::exception &e)
	{
		printf("[dEQP] EXCEPTION in batch %d: %s\n", batchIndex + 1, e.what());
		fflush(stdout);
		return false;
	}
}

int main(int argc, char **argv)
{
	int exitStatus = EXIT_SUCCESS;

	signal(SIGSEGV, crashHandler);
	signal(SIGABRT, crashHandler);

	/* sgl_lab runner (DekoGL/sgl_lab): --sgl-log FILE sends stdout/stderr to
	 * FILE, --sgl-chain NRO reloads the runner on exit. Both are removed from
	 * argv so the sub-batch mode (argc <= 1) still applies. */
	const char *sglLog = nullptr, *sglChain = nullptr;
	{
		int w = 1;
		for (int i = 1; i < argc; i++)
		{
			if (!strcmp(argv[i], "--sgl-log") && i + 1 < argc)
				sglLog = argv[++i];
			else if (!strcmp(argv[i], "--sgl-chain") && i + 1 < argc)
				sglChain = argv[++i];
			else
				argv[w++] = argv[i];
		}
		argc = w;
	}
	s_sglChain = sglChain;
	if (sglLog && freopen(sglLog, "w", stdout))
		dup2(fileno(stdout), fileno(stderr));

	if (!sglLog)
		initNxLink();
	initRomfs();

	// Set stdout to line-buffered mode
	setvbuf(stdout, nullptr, _IOLBF, 4 * 1024);

	/* Prevent the system from killing the app during long test runs.
	 * Without this, appletMainLoop() can return false at any time,
	 * especially after slow startup (29 caselist file copies to SD). */
	appletLockExit();

	printf("[dEQP] === dEQP-GLES2 for Nintendo Switch ===\n");
	printf("[dEQP] Sub-batch system: %d batches loaded\n", s_numBatches);
	fflush(stdout);

	try
	{
		// Create platform once (shared across all batches)
		printf("[dEQP] Creating platform...\n"); fflush(stdout);
		de::UniquePtr<tcu::Platform> platform(createPlatform());

		if (s_romfsCaselistReady && s_numBatches > 0 && argc <= 1)
		{
			// Sub-batch mode: run each batch sequentially
			int batchesPassed = 0;
			int batchesFailed = 0;

			for (int i = 0; i < s_numBatches; i++)
			{
				char caselistArg[128];
				snprintf(caselistArg, sizeof(caselistArg),
				         "--deqp-caselist-file=sdmc:/switch/caselist_%03d.txt", i);

				char logFilename[128];
				snprintf(logFilename, sizeof(logFilename),
				         "--deqp-log-filename=sdmc:/switch/TestResults_%03d.qpa", i);

				if (runBatch(*platform, i, s_numBatches, caselistArg, logFilename))
					batchesPassed++;
				else
					batchesFailed++;
			}

			printf("\n[dEQP] === All batches complete: %d OK, %d failed ===\n",
			       batchesPassed, batchesFailed);
			fflush(stdout);

			if (batchesFailed > 0)
				exitStatus = EXIT_FAILURE;
		}
		else
		{
			// Single-run fallback (no romfs or custom args)
			const char *caselistArg = s_defaultCaselist;
			static const char *switchArgs[6];
			switchArgs[0] = "deqp-gles2";
			switchArgs[1] = caselistArg;
			switchArgs[2] = "--deqp-log-filename=sdmc:/switch/TestResults.qpa";
			switchArgs[3] = "--deqp-archive-dir=romfs:/";
			switchArgs[4] = "--deqp-log-images=disable";
			switchArgs[5] = "--deqp-watchdog=disable";

			if (argc <= 1)
			{
				argc = 6;
				argv = const_cast<char **>(switchArgs);
			}

			tcu::CommandLine cmdLine(argc, argv);
			tcu::DirArchive archive(cmdLine.getArchiveDir());
			tcu::TestLog log(cmdLine.getLogFileName(), cmdLine.getLogFlags());
			tcu::App app(*platform, archive, log, cmdLine);

			for (;;)
			{
				if (!app.iterate())
				{
					if (cmdLine.getRunMode() == tcu::RUNMODE_EXECUTE &&
						(!app.getResult().isComplete || app.getResult().numFailed))
					{
						exitStatus = EXIT_FAILURE;
					}
					break;
				}
			}
		}
	}
	catch (const std::exception &e)
	{
		printf("[dEQP] FATAL EXCEPTION: %s\n", e.what());
		fflush(stdout);
		exitStatus = EXIT_FAILURE;
	}

	/* The platform (and thus all EGL contexts/displays) is now destroyed, but
	 * SwitchGLES keeps the deko3d device alive across eglTerminate. Destroy it
	 * here, while nvservices is still up, so the GPU is released cleanly and a
	 * relaunch (nxlink without reboot) does not inherit a wedged GPU. */
	sglShutdown();

	printf("\n[dEQP] ############################################\n");
	printf("[dEQP] ###    ALL TESTS FINISHED NORMALLY      ###\n");
	printf("[dEQP] ############################################\n");
	fflush(stdout);
	appletUnlockExit();
	deinitRomfs();
	deinitNxLink();

	fflush(stdout);
	if (sglChain)
		envSetNextLoad(sglChain, sglChain);
	return exitStatus;
}
